# Generated by Django 5.0.7 on 2024-07-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_begin_holiday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='begin',
            new_name='start',
        ),
    ]
