# Generated by Django 5.0.7 on 2024-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_begin_timelog_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencebalance',
            name='delta',
            field=models.FloatField(),
        ),
    ]
