# Generated by Django 5.0.7 on 2024-08-31 07:48

import datetime

from django.db import migrations
from django.db import models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.utils import timezone


def set_my_defaults(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    tz = timezone.get_current_timezone()
    TimeLog = apps.get_model("core", "TimeLog")
    for obj in TimeLog.objects.all().iterator():
        obj.date = obj.start.astimezone(tz).date()  # type: ignore
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024,
                    8,
                    31,
                    7,
                    48,
                    32,
                    303467,
                    tzinfo=datetime.timezone.utc,
                )
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults),
    ]
