# Generated by Django 5.1.2 on 2024-10-20 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timelog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_time_log_length',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
